### ISSUE TITLE
[Abbreviations] CSaR isn't a part of 09.03.04 direction

### ISSUE THREAD

**Issue by Zerumi** [Imtjl/1st-year-guide#3]
A little mistake in "Abbreviations" paragraph, that CSaR is a part of 09.03.04 educational direction. It isn't true. Faculty of Computer Systems and Robotics are unite of 5 directions mainly in physics field.

**Comment by worthant** [comment]
Yep, it seems that i fixed it in the new mermaid diagram in "University structure"

Is it correct now?
